sudo: required
services:
  - docker
  
before_install:
  - docker build -t gshobik/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gshobik/react-test npm test -- --coverage
  
after_success:
  - docker build -t gshobik/multi-client ./client
  - docker build -t gshobik/multi-nginx ./nginx
  - docker build -t gshobik/multi-server ./server
  - docker build -t gshobik/multi-worker ./worker
  # Push to DockerHub
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gshobik/multi-client
  - docker push gshobik/multi-nginx
  - docker push gshobik/multi-server
  - docker push gshobik/multi-worker

delpoy:
  edge: true
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-583719222897
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

