sudo: required
services:
  - docker
  
before_install:
  - docker build -t gshobik/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gshobik/react-test npm test -- --coverage
  
after_success:
  - docker build -t gshobik/multi-client ./client
  - docker build -t gshobik/multi-nginx ./nginx
  - docker build -t gshobik/multi-server ./server
  - docker build -t gshobik/multi-worker ./worker
  # Push to DockerHub
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gshobik/multi-client
  - docker push gshobik/multi-nginx
  - docker push gshobik/multi-server
  - docker push gshobik/multi-worker


